name: API Calls

on: 
  push:
    branches:
      -aqib

jobs: 
  first-job:
    runs-on: ubuntu-latest

    steps: 
      - name: Print Message
        run: echo "Test cases"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
         
      - name: Node Install
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Packages install
        run: npm install  

      - name: build file
        run: npm run build